#!/usr/bin/env python3
from pathlib import Path

def read(path): return Path(path).read_text(encoding='utf-8-sig')
def write(path, text): Path(path).write_text(text, encoding='utf-8')
def rep(path, old, new, label):
    text = read(path)
    if old not in text: raise SystemExit(f'{label}: trecho esperado não encontrado em {path}')
    write(path, text.replace(old, new, 1))

p = 'src/launcher/CentralHost.cs'
rep(p, '''                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Gerador Planilhas.ps1",\n                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1"''', '''                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Gerador Planilhas.ps1",\n                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1",\n                @"Modulos\\Controle-NF-Entrada\\Controle NF Entrada.ps1",\n                @"Modulos\\Controle-NF-Entrada\\NFEntrada.Core.ps1"''', 'CentralHost')

p = 'src/ci/audit_release.py'
rep(p, '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n}''', '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n    "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n    "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n}''', 'audit expected')
rep(p, '''    updater_path = root / "Atualizador/Central de Trabalho Updater.ps1"\n    updater_core_path = root / "Atualizador/Update.Core.ps1"\n    channels_path = root / "Atualizador/CANAIS.json"''', '''    updater_path = root / "Atualizador/Central de Trabalho Updater.ps1"\n    updater_core_path = root / "Atualizador/Update.Core.ps1"\n    channels_path = root / "Atualizador/CANAIS.json"\n    nf_path = root / "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1"\n    nf_core_path = root / "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1"''', 'audit paths')
rep(p, '''    if all(p.exists() for p in (central_path, generator_path, generator_core_path, maintenance_path, maintenance_core_path, updater_path, updater_core_path, channels_path)):''', '''    if all(p.exists() for p in (central_path, generator_path, generator_core_path, maintenance_path, maintenance_core_path, updater_path, updater_core_path, channels_path, nf_path, nf_core_path)):''', 'audit tuple')
rep(p, '''        updater = read_text(updater_path)\n        updater_core = read_text(updater_core_path)\n\n        central_version = extract_version(central, "AppVersion")''', '''        updater = read_text(updater_path)\n        updater_core = read_text(updater_core_path)\n        nf = read_text(nf_path)\n        nf_core = read_text(nf_core_path)\n\n        central_version = extract_version(central, "AppVersion")''', 'audit read')
rep(p, '''        maintenance_declared = extract_version(central, "MaintenanceVersion")\n        generator_version = extract_version(generator, "AppVersion")\n        maintenance_version = extract_version(maintenance, "AppVersion")''', '''        maintenance_declared = extract_version(central, "MaintenanceVersion")\n        nf_declared = extract_version(central, "NFEntradaVersion")\n        generator_version = extract_version(generator, "AppVersion")\n        maintenance_version = extract_version(maintenance, "AppVersion")\n        nf_version = extract_version(nf, "ModuleVersion")''', 'audit versions')
rep(p, '''        if not maintenance_declared or maintenance_declared != maintenance_version:\n            errors.append(f"versão da Manutenção divergente: Central={maintenance_declared!r}, módulo={maintenance_version!r}")\n\n        # Integração: ambos os módulos precisam continuar exportando um Control hospedável.\n        for name, text in (("Gerenciador", generator), ("Manutenção", maintenance)):''', '''        if not maintenance_declared or maintenance_declared != maintenance_version:\n            errors.append(f"versão da Manutenção divergente: Central={maintenance_declared!r}, módulo={maintenance_version!r}")\n        if not nf_declared or nf_declared != nf_version:\n            errors.append(f"versão do Controle NF Entrada divergente: Central={nf_declared!r}, módulo={nf_version!r}")\n\n        # Integração: todos os módulos precisam continuar exportando um Control hospedável.\n        for name, text in (("Gerenciador", generator), ("Manutenção", maintenance), ("NF Entrada", nf)):''', 'audit integration')
rep(p, '''        # Núcleos e configuração do Atualizador não podem desaparecer silenciosamente.''', '''        # NF Entrada — importação local, persistência e exportação pelo modelo original.\n        for marker in ("Import-NFEntradaSourceWorkbook", "Export-NFEntradaWorkbook", "modelo-nf-entrada.xlsx", 'Range("A3:F298").ClearContents()'):\n            if marker not in nf_core:\n                errors.append(f"NFEntrada.Core: contrato crítico ausente: {marker}")\n\n        # Núcleos e configuração do Atualizador não podem desaparecer silenciosamente.''', 'audit contracts')

p = 'src/ci/release_readiness.py'
rep(p, '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n}''', '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n    "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n    "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n}''', 'readiness')

p = 'src/ci/regression_contracts.py'
rep(p, '''        "maintenance_core": root / "Modulos/Central-de-Manutencao-CB5/Manutencao.Core.ps1",\n        "updater": root / "Atualizador/Central de Trabalho Updater.ps1",''', '''        "maintenance_core": root / "Modulos/Central-de-Manutencao-CB5/Manutencao.Core.ps1",\n        "nf": root / "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n        "nf_core": root / "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n        "updater": root / "Atualizador/Central de Trabalho Updater.ps1",''', 'reg paths')
rep(p, '''    maintenance_core = read(paths["maintenance_core"])\n    updater = read(paths["updater"])''', '''    maintenance_core = read(paths["maintenance_core"])\n    nf = read(paths["nf"])\n    nf_core = read(paths["nf_core"])\n    updater = read(paths["updater"])''', 'reg reads')
rep(p, '''        "Manutencao.Core.ps1",\n        "Update.Core.ps1",''', '''        "Manutencao.Core.ps1",\n        "NFEntrada.Core.ps1",\n        "Update.Core.ps1",''', 'reg marker')
rep(p, '''    # ATUALIZADOR — preserva núcleo, hash do pacote, arquivos ocultos e recuperação real.''', '''    # NF DE ENTRADA — terceiro módulo integrado, base local e exportação fiel ao modelo original.\n    for marker in ('Controle de NF de Entrada', 'IMPORTAR PLANILHA', 'EXPORTAR EXCEL', 'COMPUTADOR DE BORDO V5', 'TECLADO V5', '$script:HostedControlExport', '[switch]$HostedInCentral'):\n        require(errors, nf, marker, "NF Entrada")\n    for fn in ("Initialize-NFEntradaDataStore", "Import-NFEntradaSourceWorkbook", "Read-NFEntradaStore", "Write-NFEntradaStore", "Add-NFEntradaRecord", "Update-NFEntradaRecord", "Remove-NFEntradaRecord", "Get-NFEntradaSummary", "Export-NFEntradaWorkbook"):\n        require_function(errors, nf_core, fn, "NFEntrada.Core")\n    for marker in ('modelo-nf-entrada.xlsx', 'Range("A3:F298").ClearContents()', '$excel.Workbooks.Open($destinationFull, 0, $false)', '$excel.CalculateFullRebuild()'):\n        require(errors, nf_core, marker, "NFEntrada.Core / exportação fiel")\n\n    # ATUALIZADOR — preserva núcleo, hash do pacote, arquivos ocultos e recuperação real.''', 'reg contracts')
rep(p, '''    print("REGRESSÃO FUNCIONAL: OK — contratos de Central, Gerenciador, Componentes, Manutenção e Atualizador preservados.")''', '''    print("REGRESSÃO FUNCIONAL: OK — contratos de Central, Gerenciador, Componentes, Manutenção, NF Entrada e Atualizador preservados.")''', 'reg summary')

print('Infraestrutura permanente NF Entrada aplicada.')
