#!/usr/bin/env python3
from pathlib import Path


def read(path):
    return Path(path).read_text(encoding='utf-8-sig')


def write(path, text):
    Path(path).write_text(text, encoding='utf-8')


def replace_once(path, old, new, label):
    text = read(path)
    if old not in text:
        raise SystemExit(f'{label}: trecho esperado não encontrado em {path}')
    text = text.replace(old, new, 1)
    write(path, text)

p = '.github/workflows/build-test-package-v2.yml'
replace_once(p, '''          $smokeMaintenance = Join-Path $smokeRoot "Modulos\\Central-de-Manutencao-CB5"\n          $smokeGenerator = Join-Path $smokeRoot "Modulos\\Gerador-de-Planilhas-CB5-TV5"\n          New-Item -ItemType Directory -Force -Path $smokeUpdater, $smokeMaintenance, $smokeGenerator | Out-Null''', '''          $smokeMaintenance = Join-Path $smokeRoot "Modulos\\Central-de-Manutencao-CB5"\n          $smokeGenerator = Join-Path $smokeRoot "Modulos\\Gerador-de-Planilhas-CB5-TV5"\n          $smokeNFEntrada = Join-Path $smokeRoot "Modulos\\Controle-NF-Entrada"\n          New-Item -ItemType Directory -Force -Path $smokeUpdater, $smokeMaintenance, $smokeGenerator, $smokeNFEntrada | Out-Null''', 'workflow smoke dirs')
replace_once(p, '''          Copy-Item -LiteralPath "src\\generated\\Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1" -Destination $smokeGenerator -Force''', '''          Copy-Item -LiteralPath "src\\generated\\Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1" -Destination $smokeGenerator -Force\n          Copy-Item -LiteralPath "src\\generated\\Modulos\\Controle-NF-Entrada\\Controle NF Entrada.ps1" -Destination $smokeNFEntrada -Force\n          Copy-Item -LiteralPath "src\\generated\\Modulos\\Controle-NF-Entrada\\NFEntrada.Core.ps1" -Destination $smokeNFEntrada -Force''', 'workflow smoke copy')
replace_once(p, '''            "$SOURCE_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1"\n          )''', '''            "$SOURCE_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1"\n            "$SOURCE_ROOT/Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1"\n            "$SOURCE_ROOT/Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1"\n          )''', 'workflow required sources')
replace_once(p, '''          mkdir -p "$OUT_ROOT/Atualizador" \\\n                   "$OUT_ROOT/Modulos/Central-de-Manutencao-CB5" \\\n                   "$OUT_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5"''', '''          mkdir -p "$OUT_ROOT/Atualizador" \\\n                   "$OUT_ROOT/Modulos/Central-de-Manutencao-CB5" \\\n                   "$OUT_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5" \\\n                   "$OUT_ROOT/Modulos/Controle-NF-Entrada"''', 'workflow package dirs')
replace_once(p, '''          cp "$SOURCE_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1" "$OUT_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/"''', '''          cp "$SOURCE_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1" "$OUT_ROOT/Modulos/Gerador-de-Planilhas-CB5-TV5/"\n          cp "$SOURCE_ROOT/Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1" "$OUT_ROOT/Modulos/Controle-NF-Entrada/"\n          cp "$SOURCE_ROOT/Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1" "$OUT_ROOT/Modulos/Controle-NF-Entrada/"''', 'workflow package copy')
replace_once(p, '''              root / 'Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1',\n          ]''', '''              root / 'Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1',\n              root / 'Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1',\n              root / 'Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1',\n          ]''', 'workflow bom list')

p = 'src/launcher/CentralHost.cs'
replace_once(p, '''                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Gerador Planilhas.ps1",\n                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1"''', '''                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Gerador Planilhas.ps1",\n                @"Modulos\\Gerador-de-Planilhas-CB5-TV5\\Componentes.Core.ps1",\n                @"Modulos\\Controle-NF-Entrada\\Controle NF Entrada.ps1",\n                @"Modulos\\Controle-NF-Entrada\\NFEntrada.Core.ps1"''', 'CentralHost required files')

p = 'src/ci/audit_release.py'
replace_once(p, '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n}''', '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n    "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n    "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n}''', 'audit expected files')
replace_once(p, '''    updater_path = root / "Atualizador/Central de Trabalho Updater.ps1"\n    updater_core_path = root / "Atualizador/Update.Core.ps1"\n    channels_path = root / "Atualizador/CANAIS.json"''', '''    updater_path = root / "Atualizador/Central de Trabalho Updater.ps1"\n    updater_core_path = root / "Atualizador/Update.Core.ps1"\n    channels_path = root / "Atualizador/CANAIS.json"\n    nf_path = root / "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1"\n    nf_core_path = root / "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1"''', 'audit nf paths')
replace_once(p, '''    if all(p.exists() for p in (central_path, generator_path, generator_core_path, maintenance_path, maintenance_core_path, updater_path, updater_core_path, channels_path)):''', '''    if all(p.exists() for p in (central_path, generator_path, generator_core_path, maintenance_path, maintenance_core_path, updater_path, updater_core_path, channels_path, nf_path, nf_core_path)):''', 'audit required tuple')
replace_once(p, '''        updater = read_text(updater_path)\n        updater_core = read_text(updater_core_path)\n\n        central_version = extract_version(central, "AppVersion")''', '''        updater = read_text(updater_path)\n        updater_core = read_text(updater_core_path)\n        nf = read_text(nf_path)\n        nf_core = read_text(nf_core_path)\n\n        central_version = extract_version(central, "AppVersion")''', 'audit nf load')
replace_once(p, '''        maintenance_declared = extract_version(central, "MaintenanceVersion")\n        generator_version = extract_version(generator, "AppVersion")\n        maintenance_version = extract_version(maintenance, "AppVersion")''', '''        maintenance_declared = extract_version(central, "MaintenanceVersion")\n        nf_declared = extract_version(central, "NFEntradaVersion")\n        generator_version = extract_version(generator, "AppVersion")\n        maintenance_version = extract_version(maintenance, "AppVersion")\n        nf_version = extract_version(nf, "ModuleVersion")''', 'audit nf version vars')
replace_once(p, '''        if not maintenance_declared or maintenance_declared != maintenance_version:\n            errors.append(f"versão da Manutenção divergente: Central={maintenance_declared!r}, módulo={maintenance_version!r}")\n\n        # Integração: ambos os módulos precisam continuar exportando um Control hospedável.\n        for name, text in (("Gerenciador", generator), ("Manutenção", maintenance)):''', '''        if not maintenance_declared or maintenance_declared != maintenance_version:\n            errors.append(f"versão da Manutenção divergente: Central={maintenance_declared!r}, módulo={maintenance_version!r}")\n        if not nf_declared or nf_declared != nf_version:\n            errors.append(f"versão do Controle NF Entrada divergente: Central={nf_declared!r}, módulo={nf_version!r}")\n\n        # Integração: todos os módulos precisam continuar exportando um Control hospedável.\n        for name, text in (("Gerenciador", generator), ("Manutenção", maintenance), ("NF Entrada", nf)):''', 'audit nf integration')
replace_once(p, '''        # Núcleos e configuração do Atualizador não podem desaparecer silenciosamente.''', '''        # NF Entrada — importação local, persistência e exportação pelo modelo original.\n        for marker in ("Import-NFEntradaSourceWorkbook", "Export-NFEntradaWorkbook", "modelo-nf-entrada.xlsx", 'Range("A3:F298").ClearContents()'):\n            if marker not in nf_core:\n                errors.append(f"NFEntrada.Core: contrato crítico ausente: {marker}")\n\n        # Núcleos e configuração do Atualizador não podem desaparecer silenciosamente.''', 'audit nf contracts')

p = 'src/ci/release_readiness.py'
replace_once(p, '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n}''', '''    "Modulos/Gerador-de-Planilhas-CB5-TV5/Componentes.Core.ps1",\n    "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n    "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n}''', 'readiness expected files')

p = 'src/ci/regression_contracts.py'
replace_once(p, '''        "maintenance_core": root / "Modulos/Central-de-Manutencao-CB5/Manutencao.Core.ps1",\n        "updater": root / "Atualizador/Central de Trabalho Updater.ps1",''', '''        "maintenance_core": root / "Modulos/Central-de-Manutencao-CB5/Manutencao.Core.ps1",\n        "nf": root / "Modulos/Controle-NF-Entrada/Controle NF Entrada.ps1",\n        "nf_core": root / "Modulos/Controle-NF-Entrada/NFEntrada.Core.ps1",\n        "updater": root / "Atualizador/Central de Trabalho Updater.ps1",''', 'regression paths')
replace_once(p, '''    maintenance_core = read(paths["maintenance_core"])\n    updater = read(paths["updater"])''', '''    maintenance_core = read(paths["maintenance_core"])\n    nf = read(paths["nf"])\n    nf_core = read(paths["nf_core"])\n    updater = read(paths["updater"])''', 'regression nf reads')
replace_once(p, '''        "Manutencao.Core.ps1",\n        "Update.Core.ps1",''', '''        "Manutencao.Core.ps1",\n        "NFEntrada.Core.ps1",\n        "Update.Core.ps1",''', 'regression central nf marker')
replace_once(p, '''    # ATUALIZADOR — preserva núcleo, hash do pacote, arquivos ocultos e recuperação real.''', '''    # NF DE ENTRADA — terceiro módulo integrado, base local e exportação fiel ao modelo original.\n    for marker in (\n        'Controle de NF de Entrada', 'IMPORTAR PLANILHA', 'EXPORTAR EXCEL',\n        'COMPUTADOR DE BORDO V5', 'TECLADO V5', '$script:HostedControlExport', '[switch]$HostedInCentral',\n    ):\n        require(errors, nf, marker, "NF Entrada")\n    for fn in (\n        "Initialize-NFEntradaDataStore", "Import-NFEntradaSourceWorkbook", "Read-NFEntradaStore",\n        "Write-NFEntradaStore", "Add-NFEntradaRecord", "Update-NFEntradaRecord",\n        "Remove-NFEntradaRecord", "Get-NFEntradaSummary", "Export-NFEntradaWorkbook",\n    ):\n        require_function(errors, nf_core, fn, "NFEntrada.Core")\n    for marker in (\n        'modelo-nf-entrada.xlsx', 'Range("A3:F298").ClearContents()',\n        '$excel.Workbooks.Open($destinationFull, 0, $false)', '$excel.CalculateFullRebuild()',\n    ):\n        require(errors, nf_core, marker, "NFEntrada.Core / exportação fiel")\n\n    # ATUALIZADOR — preserva núcleo, hash do pacote, arquivos ocultos e recuperação real.''', 'regression nf contracts')
replace_once(p, '''    print("REGRESSÃO FUNCIONAL: OK — contratos de Central, Gerenciador, Componentes, Manutenção e Atualizador preservados.")''', '''    print("REGRESSÃO FUNCIONAL: OK — contratos de Central, Gerenciador, Componentes, Manutenção, NF Entrada e Atualizador preservados.")''', 'regression summary')

print('Preparação permanente da infraestrutura do módulo NF Entrada aplicada.')
